begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
\ir fixtures/paddle_recovery_fixture.psql
create temp table cases(label text,u uuid,extras integer);
insert into cases values('base',pg_temp.recovery_owner(),0),('seat',pg_temp.recovery_owner(1),1);
select is(pg_temp.obligation(u)->>'reason','incomplete_evidence','past-due alone is incomplete: '||label) from cases;
select is(pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'debt')),'pending','debt observation has no payment effect: '||label) from cases;
select is(pg_temp.obligation(u)->>'available','true','one exact obligation: '||label) from cases;
select is(pg_temp.obligation(u)#>>'{obligation,amountMinor}',case when extras=0 then '5900' else '7100' end,'full base plus approved seats amount: '||label) from cases;
select is(pg_temp.recovery_counts(u)->>'renewal','0','no renewal application from debt: '||label) from cases;
select is(pg_temp.obligation(u)#>>'{obligation,authorityRevision}',pg_temp.obligation(u)#>>'{obligation,authorityRevision}','repeat resolution deterministic: '||label) from cases;
select ok(not has_function_privilege('authenticated','resolve_billing_outstanding_obligation_v1(uuid)','execute'),'private resolver inaccessible to browser');
select ok(not has_function_privilege('anon','resolve_billing_outstanding_obligation_v1(uuid)','execute'),'private resolver inaccessible to anon');
select ok(has_function_privilege('service_role','resolve_billing_outstanding_obligation_v1(uuid)','execute'),'service can resolve private obligation');

create temp table bad_cases(label text,u uuid);
insert into bad_cases select label,pg_temp.recovery_owner() from unnest(array['two','customer','amount','currency','period','items','incomplete','equal-revision','adjustment','canceled','paid']) label;
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'baseline')) from bad_cases;
select pg_temp.recovery_dispatch(jsonb_set(pg_temp.recovery_observation(u,'second'),'{transactionRef}',to_jsonb('synthetic/other/'||u))) from bad_cases where label='two';
select is(pg_temp.obligation(u)->>'reason','ambiguous','two debts never selected by recency') from bad_cases where label='two';
select throws_ok($q$select pg_temp.recovery_dispatch(jsonb_set(pg_temp.recovery_observation(u,'wrong-customer','transaction.updated'),'{customerRef}','"synthetic/other-customer"')) from bad_cases where label='customer'$q$,'P0001','BILLING_PROOF_IDENTITY_MISMATCH','provenance rejects changed transaction customer before retention');
select pg_temp.recovery_dispatch(jsonb_set(pg_temp.recovery_observation(u,'wrong-currency','transaction.updated'),'{currency}','"EUR"')) from bad_cases where label='currency';
select is(pg_temp.obligation(u)->>'reason','contradictory_evidence','same transaction cannot change currency') from bad_cases where label='currency';
select pg_temp.recovery_dispatch(jsonb_set(pg_temp.recovery_observation(u,'wrong-period','transaction.updated'),'{billingPeriod,endsAt}','"2026-11-21T00:00:00Z"')) from bad_cases where label='period';
select is(pg_temp.obligation(u)->>'reason','contradictory_evidence','same transaction cannot change period') from bad_cases where label='period';
select pg_temp.recovery_dispatch(jsonb_set(pg_temp.recovery_observation(u,'wrong-items','transaction.updated'),'{items,0,quantity}','2')) from bad_cases where label='items';
select is(pg_temp.obligation(u)->>'reason','contradictory_evidence','same transaction cannot change item quantity') from bad_cases where label='items';
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'missing','transaction.updated')-'financial') from bad_cases where label='incomplete';
select is(pg_temp.obligation(u)->>'reason','incomplete_evidence','sparse retained history is not backfilled') from bad_cases where label='incomplete';
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'equal-paid','transaction.paid')) from bad_cases where label='equal-revision';
select is(pg_temp.obligation(u)->>'reason','contradictory_evidence','equal resource revision conflicting financial state blocks') from bad_cases where label='equal-revision';
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'paid','transaction.paid','2026-10-21T12:00:00Z')) from bad_cases where label='paid';
select is(pg_temp.obligation(u)->>'reason','settlement_pending','paid is not another collectible obligation') from bad_cases where label='paid';
select is(pg_temp.recovery_counts(u)->>'renewal','0','paid cannot establish financial recovery') from bad_cases where label='paid';
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'cancel','transaction.canceled','2026-10-21T12:00:00Z')) from bad_cases where label='canceled';
select is(pg_temp.obligation(u)->>'reason','canceled','canceled transaction cannot be collected') from bad_cases where label='canceled';
select pg_temp.recovery_dispatch((pg_temp.recovery_observation(u,'adjust')-array['financial','paymentTotals','items','billingPeriod','origin','currency'])||jsonb_build_object('kind','adjustment.created','eventType','adjustment.created','adjustmentRef','synthetic/adjustment/'||u,'status','approved','resourceUpdatedAt','2026-10-21T12:00:00Z')) from bad_cases where label='adjustment';
select is(pg_temp.obligation(u)->>'reason','unsupported','adjustment invalidates automatic recovery') from bad_cases where label='adjustment';
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'amount','transaction.updated')||'{"financial":{"resourceUpdatedAt":"2026-10-21T12:00:00Z","collectionMode":"automatic","captured":"0","totals":{"subtotal":"5900","tax":"1","discount":"0","total":"5901","credit":"0","creditToBalance":"0","grandTotal":"5901","balance":"5901"},"payments":[]},"paymentTotals":{"total":5901,"balance":5901,"paid":0}}'::jsonb) from bad_cases where label='amount';
select is(pg_temp.obligation(u)->>'reason','contradictory_evidence','later revision cannot change obligation amount') from bad_cases where label='amount';
select pg_temp.recovery_ingest(jsonb_set(pg_temp.recovery_observation(u,'wrong-sub'),'{subscriptionRef}','"synthetic/wrong-subscription"')) from cases where label='base';
select is(pg_temp.obligation(u)->>'reason','contradictory_evidence','transaction identity cannot change subscription') from cases where label='base';
select throws_ok($q$select pg_temp.recovery_ingest(jsonb_set(pg_temp.recovery_observation(u,'wrong-env'),'{environment}','"live"')) from cases where label='base'$q$,'P0001','PADDLE_RECOVERY_INGRESS_INVALID','live evidence denied');
select throws_ok($q$select pg_temp.recovery_ingest(jsonb_set(pg_temp.recovery_observation(u,'null-collection'),'{financial,collectionMode}','null')) from cases where label='base'$q$,'P0001','PADDLE_RECOVERY_FACTS','null collection fails closed');
select throws_ok($q$select pg_temp.recovery_ingest(jsonb_set(pg_temp.recovery_observation(u,'bad-balance'),'{financial,totals,balance}','"1"')) from cases where label='base'$q$,'P0001','PADDLE_RECOVERY_FACTS','inconsistent exact totals rejected before retention');
create temp table history_cases(label text,u uuid);
insert into history_cases select label,pg_temp.recovery_owner(1) from unnest(array['multiset','partial','credit','stale','no-provenance']) label;
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'baseline')) from history_cases;
select pg_temp.recovery_dispatch(jsonb_set(pg_temp.recovery_observation(u,'reordered','transaction.updated'),'{items}',(select jsonb_agg(value order by ord desc) from jsonb_array_elements(pg_temp.recovery_observation(u,'x')->'items') with ordinality i(value,ord)))) from history_cases where label='multiset';
select is(pg_temp.obligation(u)->>'available','true','item reorder is semantically equivalent') from history_cases where label='multiset';
select pg_temp.recovery_dispatch(jsonb_set(pg_temp.recovery_observation(u,'older','transaction.payment_failed','2026-10-20T11:59:59.999999999Z'),'{occurredAt}','"2026-10-22T00:00:00Z"')) from history_cases where label='stale';
select is(pg_temp.obligation(u)->>'available','true','late-delivered older failure does not replace resource clock') from history_cases where label='stale';
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'partial','transaction.updated','2026-10-21T12:00:00Z')||'{"financial":{"resourceUpdatedAt":"2026-10-21T12:00:00Z","collectionMode":"automatic","captured":"100","totals":{"subtotal":"7100","tax":"0","discount":"0","total":"7100","credit":"0","creditToBalance":"0","grandTotal":"7100","balance":"7000"},"payments":[{"attemptReference":"synthetic/partial","amount":"100","status":"captured"}]},"paymentTotals":{"total":7100,"balance":7000,"paid":100}}'::jsonb) from history_cases where label='partial';
select is(pg_temp.obligation(u)->>'reason','unsupported','partial payment unavailable') from history_cases where label='partial';
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'credit','transaction.updated','2026-10-21T12:00:00Z')||'{"financial":{"resourceUpdatedAt":"2026-10-21T12:00:00Z","collectionMode":"automatic","captured":"0","totals":{"subtotal":"7100","tax":"0","discount":"0","total":"7100","credit":"100","creditToBalance":"0","grandTotal":"7000","balance":"7000"},"payments":[]},"paymentTotals":{"total":7000,"balance":7000,"paid":0}}'::jsonb) from history_cases where label='credit';
select is(pg_temp.obligation(u)->>'reason','unsupported','credit accounting unavailable') from history_cases where label='credit';
-- Existing production proof guard rejects fabricated receipt linkage, rather than bypassing it in fixtures.
select throws_ok($q$select ingest_verified_paddle_recovery_event_v1('{}'::jsonb,repeat('a',64),'synthetic/no-proof',pg_temp.recovery_observation(u,'no-proof')) from history_cases where label='no-provenance'$q$,'P0001','BILLING_PROOF_INVALID','no fabricated authenticated provenance');
create temp table conflicts(label text,u uuid);
insert into conflicts select label,pg_temp.plan_owner() from unnest(array['plan','seat']) label;
select pg_temp.plan_begin(u) from conflicts where label='plan';
select pg_temp.paddle_seat_begin(u,1,gen_random_uuid()) from conflicts where label='seat';
select is(pg_temp.obligation(u)->>'reason','operation_conflict','open commercial operation prevents recovery: '||label) from conflicts;
select is(resolve_billing_outstanding_obligation_v1(gen_random_uuid())->>'reason','unsupported','unknown canonical authority fails closed');
create temp table consumed_case(u uuid);
insert into consumed_case values(pg_temp.recovery_owner());
select pg_temp.recovery_ingest(jsonb_set(pg_temp.recovery_observation(u,'consumed'),'{transactionRef}',to_jsonb('synthetic/txn/'||u))) from consumed_case;
select is(pg_temp.obligation(u)->>'reason','contradictory_evidence','initial purchase consumption cannot become a renewal obligation') from consumed_case;
create temp table boundary_cases(label text,u uuid,revision text);
insert into boundary_cases(label,u) select label,pg_temp.recovery_owner(1) from unnest(array['newer-paused','unknown-marker','retained-marker','revision','duplicates']) label;
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'debt')) from boundary_cases where label<>'retained-marker';
update boundary_cases set revision=pg_temp.obligation(u)#>>'{obligation,authorityRevision}';
select pg_temp.recovery_ingest(pg_temp.recovery_observation(u,'paused','subscription.updated','2026-10-22T12:00:00Z')||'{"status":"paused","pausedAt":"2026-10-22T12:00:00Z"}'::jsonb) from boundary_cases where label='newer-paused';
select is(pg_temp.obligation(u)->>'reason','unsupported','newer retained paused state cannot be hidden by applied past-due authority') from boundary_cases where label='newer-paused';
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'marker','transaction.updated')||jsonb_build_object('seatQuantityOperationId',gen_random_uuid())) from boundary_cases where label='unknown-marker';
select is(pg_temp.obligation(u)->>'reason','operation_conflict','unknown operation marker does not acquire renewal authority') from boundary_cases where label='unknown-marker';
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'debt')||jsonb_build_object('seatQuantityOperationId',(select operation_id from billing_operations_v2 where created_by_user_id=u and operation_kind='seat_quantity' and status='completed'))) from boundary_cases where label='retained-marker';
select is(pg_temp.obligation(u)->>'available','true','completed seat marker does not block ordinary approved-seat renewal') from boundary_cases where label='retained-marker';
select pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'new-evidence','transaction.updated','2026-10-20T12:00:00.000000001Z')) from boundary_cases where label='revision';
select isnt(pg_temp.obligation(u)#>>'{obligation,authorityRevision}',revision,'authority revision changes after new authenticated knowledge') from boundary_cases where label='revision';
select pg_temp.recovery_dispatch(jsonb_set(pg_temp.recovery_observation(u,'duplicate-item','transaction.updated'),'{items}',(pg_temp.recovery_observation(u,'x')->'items')||jsonb_build_array(pg_temp.recovery_observation(u,'x')#>'{items,1}'))) from boundary_cases where label='duplicates';
select is(pg_temp.obligation(u)->>'reason','contradictory_evidence','item multiset duplicate multiplicity remains significant') from boundary_cases where label='duplicates';
select is(pg_temp.recovery_counts(u)->>'renewal','0','invalid evidence never grants renewal: '||label) from bad_cases;
select * from finish();rollback;
