begin;
select no_plan();
create temp table access_actors(name text primary key,owner_id uuid,workspace_id uuid,client_user_id uuid,client_id uuid,template_id uuid);
grant select on access_actors to authenticated;
create function pg_temp.access_fixture(p_name text) returns void language plpgsql as $$
declare o uuid:=gen_random_uuid(); u uuid:=gen_random_uuid(); a uuid; w uuid; c uuid; t uuid; staff uuid:=gen_random_uuid();
begin
 insert into auth.users(id,email) values(o,o::text||'@access.test'),(u,u::text||'@access.test');
 insert into public.pt_profiles(user_id,full_name) values(o,'Access coach');
 a:=public.ensure_commercial_billing_account(o,'manual');
 insert into public.account_subscriptions(billing_account_id,plan_version_id,subscription_kind,status,source) select a,id,'complimentary','active','legacy_beta_backfill' from public.commercial_plan_versions where plan_key='scale' and status='active';
 insert into public.workspaces(name,owner_user_id) values('Access workspace',o) returning id into w;
 insert into public.clients(workspace_id,user_id,display_name,status) values(w,u,'Existing client','active') returning id into c;
 insert into public.workout_templates(workspace_id,name) values(w,'Existing template') returning id into t;
 insert into public.pt_hub_profiles(user_id,slug,is_published,marketplace_visible) values(o,'access-'||substr(o::text,1,8),true,true);
 insert into public.pt_hub_settings(user_id,profile_visibility) values(o,'listed');
 insert into auth.users(id,email) values(staff,staff::text||'@access.test');
 insert into public.workspace_members(workspace_id,user_id,role,status) values(w,staff,'assistant_coach','active');
 insert into public.workspace_member_invites(workspace_id,email,role,client_access_mode,token_hash,status,invited_by_user_id,expires_at) values(w,'pending-'||staff::text||'@access.test','assistant_coach','assigned_clients_only',md5(staff::text)||md5(w::text),'pending',o,now()+interval '1 day');
 insert into public.pt_packages(pt_user_id,title,status,is_public) values(o,'Access package','active',true);
 insert into public.invites(workspace_id,code,token,created_by_user_id,expires_at) values(w,'access-'||p_name,'access-token-'||p_name,o,now()+interval '1 day');
 insert into access_actors values(p_name,o,w,u,c,t);
end $$;
select pg_temp.access_fixture('full');
select pg_temp.access_fixture('grace');
select pg_temp.access_fixture('restricted');
select pg_temp.access_fixture('expired');
-- Real delivery parents exercise indirect scopes and normalization ordering.
do $$ declare x record; t uuid; begin
 for x in select * from access_actors loop
  perform set_config('request.jwt.claim.sub',x.owner_id::text,true);
  insert into public.assigned_workouts(client_id,workout_template_id,scheduled_date) values(x.client_id,x.template_id,current_date);
  insert into public.conversations(workspace_id,client_id) values(x.workspace_id,x.client_id) on conflict do nothing;
  insert into public.checkin_templates(workspace_id,name) values(x.workspace_id,'Access check-in') returning id into t;
  update public.clients set checkin_template_id=t,checkin_start_date=public.normalize_checkin_due_date(current_date-7),checkin_frequency='weekly' where id=x.client_id;
  insert into public.checkin_photos(checkin_id,client_id,photo_type,url,storage_path) select ci.id,ci.client_id,p.kind,'https://example.invalid/fixture','fixture/'||p.kind from public.checkins ci cross join (values('front'),('side'),('back')) p(kind) where ci.client_id=x.client_id and ci.week_ending_saturday<=current_date;
 end loop;
 perform set_config('request.jwt.claim.sub','',true);
end $$;
insert into public.workspaces(name,owner_user_id) select 'Empty access closure',owner_id from access_actors where name='expired';
insert into public.workout_templates(workspace_id,name) select id,'Unassigned close fixture' from public.workspaces where name='Empty access closure';
update public.account_subscriptions s set status=x.name, restricted_at=case when x.name='restricted' then now() end, expired_at=case when x.name='expired' then now() end from public.billing_accounts a join access_actors x on x.owner_id=a.owner_user_id where s.billing_account_id=a.id and x.name<>'full';
select is(public.is_commercial_action_allowed('onboarding','billing_manage'),true,'onboarding: billing_manage');
select is(public.is_commercial_action_allowed('onboarding','account_security'),true,'onboarding: account_security');
select is(public.is_commercial_action_allowed('onboarding','data_export'),true,'onboarding: data_export');
select is(public.is_commercial_action_allowed('onboarding','remediation'),true,'onboarding: remediation');
select is(public.is_commercial_action_allowed('onboarding','workspace_read'),false,'onboarding: workspace_read');
select is(public.is_commercial_action_allowed('onboarding','delivery_write'),false,'onboarding: delivery_write');
select is(public.is_commercial_action_allowed('onboarding','business_configuration_write'),false,'onboarding: business_configuration_write');
select is(public.is_commercial_action_allowed('onboarding','acquisition_write'),false,'onboarding: acquisition_write');
select is(public.is_commercial_action_allowed('onboarding','capacity_growth'),false,'onboarding: capacity_growth');
select is(public.is_commercial_action_allowed('onboarding','client_self_service'),true,'onboarding: client_self_service');
select is(public.is_commercial_action_allowed('onboarding','client_coached_read'),true,'onboarding: client_coached_read');
select is(public.is_commercial_action_allowed('onboarding','client_coached_write'),false,'onboarding: client_coached_write');
select is(public.is_commercial_action_allowed('full','billing_manage'),true,'full: billing_manage');
select is(public.is_commercial_action_allowed('full','account_security'),true,'full: account_security');
select is(public.is_commercial_action_allowed('full','data_export'),true,'full: data_export');
select is(public.is_commercial_action_allowed('full','remediation'),true,'full: remediation');
select is(public.is_commercial_action_allowed('full','workspace_read'),true,'full: workspace_read');
select is(public.is_commercial_action_allowed('full','delivery_write'),true,'full: delivery_write');
select is(public.is_commercial_action_allowed('full','business_configuration_write'),true,'full: business_configuration_write');
select is(public.is_commercial_action_allowed('full','acquisition_write'),true,'full: acquisition_write');
select is(public.is_commercial_action_allowed('full','capacity_growth'),true,'full: capacity_growth');
select is(public.is_commercial_action_allowed('full','client_self_service'),true,'full: client_self_service');
select is(public.is_commercial_action_allowed('full','client_coached_read'),true,'full: client_coached_read');
select is(public.is_commercial_action_allowed('full','client_coached_write'),true,'full: client_coached_write');
select is(public.is_commercial_action_allowed('existing_delivery_only','billing_manage'),true,'existing_delivery_only: billing_manage');
select is(public.is_commercial_action_allowed('existing_delivery_only','account_security'),true,'existing_delivery_only: account_security');
select is(public.is_commercial_action_allowed('existing_delivery_only','data_export'),true,'existing_delivery_only: data_export');
select is(public.is_commercial_action_allowed('existing_delivery_only','remediation'),true,'existing_delivery_only: remediation');
select is(public.is_commercial_action_allowed('existing_delivery_only','workspace_read'),true,'existing_delivery_only: workspace_read');
select is(public.is_commercial_action_allowed('existing_delivery_only','delivery_write'),true,'existing_delivery_only: delivery_write');
select is(public.is_commercial_action_allowed('existing_delivery_only','business_configuration_write'),false,'existing_delivery_only: business_configuration_write');
select is(public.is_commercial_action_allowed('existing_delivery_only','acquisition_write'),false,'existing_delivery_only: acquisition_write');
select is(public.is_commercial_action_allowed('existing_delivery_only','capacity_growth'),false,'existing_delivery_only: capacity_growth');
select is(public.is_commercial_action_allowed('existing_delivery_only','client_self_service'),true,'existing_delivery_only: client_self_service');
select is(public.is_commercial_action_allowed('existing_delivery_only','client_coached_read'),true,'existing_delivery_only: client_coached_read');
select is(public.is_commercial_action_allowed('existing_delivery_only','client_coached_write'),true,'existing_delivery_only: client_coached_write');
select is(public.is_commercial_action_allowed('read_only','billing_manage'),true,'read_only: billing_manage');
select is(public.is_commercial_action_allowed('read_only','account_security'),true,'read_only: account_security');
select is(public.is_commercial_action_allowed('read_only','data_export'),true,'read_only: data_export');
select is(public.is_commercial_action_allowed('read_only','remediation'),true,'read_only: remediation');
select is(public.is_commercial_action_allowed('read_only','workspace_read'),true,'read_only: workspace_read');
select is(public.is_commercial_action_allowed('read_only','delivery_write'),false,'read_only: delivery_write');
select is(public.is_commercial_action_allowed('read_only','business_configuration_write'),false,'read_only: business_configuration_write');
select is(public.is_commercial_action_allowed('read_only','acquisition_write'),false,'read_only: acquisition_write');
select is(public.is_commercial_action_allowed('read_only','capacity_growth'),false,'read_only: capacity_growth');
select is(public.is_commercial_action_allowed('read_only','client_self_service'),true,'read_only: client_self_service');
select is(public.is_commercial_action_allowed('read_only','client_coached_read'),true,'read_only: client_coached_read');
select is(public.is_commercial_action_allowed('read_only','client_coached_write'),false,'read_only: client_coached_write');
select is(public.is_commercial_action_allowed('none','billing_manage'),true,'none: billing_manage');
select is(public.is_commercial_action_allowed('none','account_security'),true,'none: account_security');
select is(public.is_commercial_action_allowed('none','data_export'),true,'none: data_export');
select is(public.is_commercial_action_allowed('none','remediation'),true,'none: remediation');
select is(public.is_commercial_action_allowed('none','workspace_read'),false,'none: workspace_read');
select is(public.is_commercial_action_allowed('none','delivery_write'),false,'none: delivery_write');
select is(public.is_commercial_action_allowed('none','business_configuration_write'),false,'none: business_configuration_write');
select is(public.is_commercial_action_allowed('none','acquisition_write'),false,'none: acquisition_write');
select is(public.is_commercial_action_allowed('none','capacity_growth'),false,'none: capacity_growth');
select is(public.is_commercial_action_allowed('none','client_self_service'),true,'none: client_self_service');
select is(public.is_commercial_action_allowed('none','client_coached_read'),true,'none: client_coached_read');
select is(public.is_commercial_action_allowed('none','client_coached_write'),false,'none: client_coached_write');
select throws_ok($$select public.is_commercial_action_allowed('full','unknown')$$,'22023','ACCOUNT_ACCESS_ACTION_NOT_ALLOWED','unknown action rejected');
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='full'),true);
set local role authenticated;
select is(public.get_my_commercial_access_summary()->>'accessMode','full','full canonical owner mode');
select is((select public.get_workspace_commercial_access(workspace_id)->>'accessMode' from access_actors where name='full'),'full','full workspace owner mode');
select lives_ok($$update public.workout_templates set name='Delivery edited' where id=(select template_id from access_actors where name='full')$$,'full existing delivery allowed');
select lives_ok($$update public.workspaces set name='Business edited' where id=(select workspace_id from access_actors where name='full')$$,'full business configuration allowed');
reset role;
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='full'),true);
set local role authenticated;
select lives_ok($$select public.update_workspace_team_member_status(x.workspace_id,m.id,'suspended') from access_actors x join public.workspace_members m on m.workspace_id=x.workspace_id where x.name='full' and m.user_id<>x.owner_id$$,'full: member suspension remains available');
select lives_ok($$select public.revoke_workspace_team_invite(x.workspace_id,i.id) from access_actors x join public.workspace_member_invites i on i.workspace_id=x.workspace_id where x.name='full'$$,'full: invite revocation remains available');
select lives_ok($$select public.update_my_pt_package(p.id,'{"status":"archived","is_public":false}') from public.pt_packages p join access_actors x on x.owner_id=p.pt_user_id where x.name='full'$$,'full: package archival remains available');
reset role;
select set_config('request.jwt.claim.sub',(select client_user_id::text from access_actors where name='full'),true);
set local role authenticated;
select lives_ok($$select public.accept_invite(p_token=>'access-token-full')$$,'full: token invite consumption remains authorized');
select lives_ok($$insert into public.habit_logs(client_id,log_date,steps) select client_id,current_date,100 from access_actors where name='full'$$,'full client habit submission allowed');
select lives_ok($$insert into public.workout_sessions(assigned_workout_id) select w.id from public.assigned_workouts w join access_actors x on x.client_id=w.client_id where x.name='full'$$,'full: workout session resolves assigned parent before normalization');
select lives_ok($$update public.checkins set submitted_at=now() where id=(select ci.id from public.checkins ci join access_actors x on x.client_id=ci.client_id where x.name='full' order by ci.week_ending_saturday limit 1)$$,'full: complete check-in submission');
select ok((select (public.get_client_coaching_access(client_id)->>'canUseIndependentSelfService')::boolean from access_actors where name='full'),'full independent client access remains');
select ok((select not (public.get_client_coaching_access(client_id) ?| array['planKey','price','accessMode','billingOwnerUserId','reason']) from access_actors where name='full'),'full client response excludes commercial details');
reset role;
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='grace'),true);
set local role authenticated;
select is(public.get_my_commercial_access_summary()->>'accessMode','existing_delivery_only','grace canonical owner mode');
select throws_ok($$update public.pt_profiles set headline='New public headline' where user_id=auth.uid()$$,'42501','ACCOUNT_ACCESS_EXISTING_DELIVERY_ONLY','grace cannot use legacy profile business fields as a bypass');
select lives_ok($$update public.pt_profiles set full_name='Updated personal identity' where user_id=auth.uid()$$,'grace retains personal identity editing');
select is((select public.get_workspace_commercial_access(workspace_id)->>'accessMode' from access_actors where name='grace'),'existing_delivery_only','grace workspace owner mode');
select lives_ok($$update public.workout_templates set name='Delivery edited' where id=(select template_id from access_actors where name='grace')$$,'grace existing delivery allowed');
select throws_ok($$update public.workspaces set name='Business edited' where id=(select workspace_id from access_actors where name='grace')$$,'42501','ACCOUNT_ACCESS_EXISTING_DELIVERY_ONLY','grace direct business write denied');
reset role;
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='grace'),true);
set local role authenticated;
select lives_ok($$select public.update_workspace_team_member_status(x.workspace_id,m.id,'suspended') from access_actors x join public.workspace_members m on m.workspace_id=x.workspace_id where x.name='grace' and m.user_id<>x.owner_id$$,'grace: member suspension remains available');
select lives_ok($$select public.revoke_workspace_team_invite(x.workspace_id,i.id) from access_actors x join public.workspace_member_invites i on i.workspace_id=x.workspace_id where x.name='grace'$$,'grace: invite revocation remains available');
select lives_ok($$select public.update_my_pt_package(p.id,'{"status":"archived","is_public":false}') from public.pt_packages p join access_actors x on x.owner_id=p.pt_user_id where x.name='grace'$$,'grace: package archival remains available');
reset role;
select set_config('request.jwt.claim.sub',(select client_user_id::text from access_actors where name='grace'),true);
set local role authenticated;
select throws_ok($$select public.accept_invite(p_token=>'access-token-grace')$$,'42501','CLIENT_COACHING_INTERACTION_UNAVAILABLE','grace: existing identity token consumption is still acquisition');
select lives_ok($$insert into public.habit_logs(client_id,log_date,steps) select client_id,current_date,100 from access_actors where name='grace'$$,'grace client habit submission allowed');
select lives_ok($$insert into public.workout_sessions(assigned_workout_id) select w.id from public.assigned_workouts w join access_actors x on x.client_id=w.client_id where x.name='grace'$$,'grace: workout session resolves assigned parent before normalization');
select lives_ok($$update public.checkins set submitted_at=now() where id=(select ci.id from public.checkins ci join access_actors x on x.client_id=ci.client_id where x.name='grace' order by ci.week_ending_saturday limit 1)$$,'grace: complete check-in submission');
select ok((select (public.get_client_coaching_access(client_id)->>'canUseIndependentSelfService')::boolean from access_actors where name='grace'),'grace independent client access remains');
select ok((select not (public.get_client_coaching_access(client_id) ?| array['planKey','price','accessMode','billingOwnerUserId','reason']) from access_actors where name='grace'),'grace client response excludes commercial details');
reset role;
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='restricted'),true);
set local role authenticated;
select is(public.get_my_commercial_access_summary()->>'accessMode','read_only','restricted canonical owner mode');
select is((select public.get_workspace_commercial_access(workspace_id)->>'accessMode' from access_actors where name='restricted'),'read_only','restricted workspace owner mode');
select throws_ok($$update public.workout_templates set name='Delivery edited' where id=(select template_id from access_actors where name='restricted')$$,'42501','ACCOUNT_ACCESS_READ_ONLY','restricted direct template write denied');
select throws_ok($$update public.workspaces set name='Business edited' where id=(select workspace_id from access_actors where name='restricted')$$,'42501','ACCOUNT_ACCESS_READ_ONLY','restricted direct business write denied');
reset role;
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='restricted'),true);
set local role authenticated;
select lives_ok($$select public.update_workspace_team_member_status(x.workspace_id,m.id,'suspended') from access_actors x join public.workspace_members m on m.workspace_id=x.workspace_id where x.name='restricted' and m.user_id<>x.owner_id$$,'restricted: member suspension remains available');
select lives_ok($$select public.revoke_workspace_team_invite(x.workspace_id,i.id) from access_actors x join public.workspace_member_invites i on i.workspace_id=x.workspace_id where x.name='restricted'$$,'restricted: invite revocation remains available');
select lives_ok($$select public.update_my_pt_package(p.id,'{"status":"archived","is_public":false}') from public.pt_packages p join access_actors x on x.owner_id=p.pt_user_id where x.name='restricted'$$,'restricted: package archival remains available');
reset role;
select set_config('request.jwt.claim.sub',(select client_user_id::text from access_actors where name='restricted'),true);
set local role authenticated;
select throws_ok($$insert into public.habit_logs(client_id,log_date,steps) select client_id,current_date,100 from access_actors where name='restricted'$$,'42501','CLIENT_COACHING_INTERACTION_UNAVAILABLE','restricted client habit submission denied safely');
select throws_ok($$insert into public.workout_sessions(assigned_workout_id) select w.id from public.assigned_workouts w join access_actors x on x.client_id=w.client_id where x.name='restricted'$$,'42501','CLIENT_COACHING_INTERACTION_UNAVAILABLE','restricted: workout session resolves assigned parent before normalization denied');
select throws_ok($$update public.checkins set submitted_at=now() where id=(select ci.id from public.checkins ci join access_actors x on x.client_id=ci.client_id where x.name='restricted' order by ci.week_ending_saturday limit 1)$$,'42501','CLIENT_COACHING_INTERACTION_UNAVAILABLE','restricted: complete check-in submission denied');
select ok((select (public.get_client_coaching_access(client_id)->>'canUseIndependentSelfService')::boolean from access_actors where name='restricted'),'restricted independent client access remains');
select ok((select not (public.get_client_coaching_access(client_id) ?| array['planKey','price','accessMode','billingOwnerUserId','reason']) from access_actors where name='restricted'),'restricted client response excludes commercial details');
reset role;
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='expired'),true);
set local role authenticated;
select is(public.get_my_commercial_access_summary()->>'accessMode','none','expired canonical owner mode');
select lives_ok($$select public.ensure_workspace_checkins(workspace_id,current_date,current_date+30) from access_actors where name='expired'$$,'expired workspace read does not attempt check-in materialization');
select lives_ok($$select public.ensure_workspace_client_onboarding(client_id) from access_actors where name='expired'$$,'expired onboarding read retains existing history without creating rows');
select is((select public.get_workspace_commercial_access(workspace_id)->>'accessMode' from access_actors where name='expired'),'none','expired workspace owner mode');
select throws_ok($$update public.workout_templates set name='Delivery edited' where id=(select template_id from access_actors where name='expired')$$,'42501','ACCOUNT_ACCESS_EXPIRED','expired direct template write denied');
select throws_ok($$update public.workspaces set name='Business edited' where id=(select workspace_id from access_actors where name='expired')$$,'42501','ACCOUNT_ACCESS_EXPIRED','expired direct business write denied');
reset role;
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='expired'),true);
set local role authenticated;
select lives_ok($$select public.update_workspace_team_member_status(x.workspace_id,m.id,'suspended') from access_actors x join public.workspace_members m on m.workspace_id=x.workspace_id where x.name='expired' and m.user_id<>x.owner_id$$,'expired: member suspension remains available');
select lives_ok($$select public.revoke_workspace_team_invite(x.workspace_id,i.id) from access_actors x join public.workspace_member_invites i on i.workspace_id=x.workspace_id where x.name='expired'$$,'expired: invite revocation remains available');
select lives_ok($$select public.update_my_pt_package(p.id,'{"status":"archived","is_public":false}') from public.pt_packages p join access_actors x on x.owner_id=p.pt_user_id where x.name='expired'$$,'expired: package archival remains available');
reset role;
select set_config('request.jwt.claim.sub',(select client_user_id::text from access_actors where name='expired'),true);
set local role authenticated;
select throws_ok($$insert into public.habit_logs(client_id,log_date,steps) select client_id,current_date,100 from access_actors where name='expired'$$,'42501','CLIENT_COACHING_INTERACTION_UNAVAILABLE','expired client habit submission denied safely');
select throws_ok($$insert into public.workout_sessions(assigned_workout_id) select w.id from public.assigned_workouts w join access_actors x on x.client_id=w.client_id where x.name='expired'$$,'42501','CLIENT_COACHING_INTERACTION_UNAVAILABLE','expired: workout session resolves assigned parent before normalization denied');
select throws_ok($$update public.checkins set submitted_at=now() where id=(select ci.id from public.checkins ci join access_actors x on x.client_id=ci.client_id where x.name='expired' order by ci.week_ending_saturday limit 1)$$,'42501','CLIENT_COACHING_INTERACTION_UNAVAILABLE','expired: complete check-in submission denied');
select ok((select (public.get_client_coaching_access(client_id)->>'canUseIndependentSelfService')::boolean from access_actors where name='expired'),'expired independent client access remains');
select ok((select not (public.get_client_coaching_access(client_id) ?| array['planKey','price','accessMode','billingOwnerUserId','reason']) from access_actors where name='expired'),'expired client response excludes commercial details');
reset role;
select set_config('request.jwt.claim.sub','',true);
select is((select count(*)::integer from public.pt_hub_profiles where user_id in (select owner_id from access_actors) and is_published),4,'access loss preserves all publication preferences');
select is((select count(*)::integer from public.pt_hub_profiles where user_id in (select owner_id from access_actors) and public.is_coach_accepting_applications(user_id)),1,'only full owner accepts applications');
select ok(not has_function_privilege('authenticated','public.resolve_account_commercial_access(uuid)','execute'),'private resolver cannot select foreign owner');
select ok(not has_function_privilege('authenticated','public.assert_commercial_action_allowed(uuid,text,uuid,uuid)','execute'),'private assertion cannot become authorization bypass');

-- Resolve each shared workspace independently of the caller's personal plan.
insert into public.workspace_members(workspace_id,user_id,role,status) select f.workspace_id,e.owner_id,'admin','active' from access_actors f cross join access_actors e where f.name='full' and e.name='expired';
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='expired'),true);
set local role authenticated;
select is((select public.get_workspace_commercial_access(workspace_id)->>'accessMode' from access_actors where name='full'),'full','expired personal owner accesses full shared workspace');
select ok((select not (public.get_workspace_commercial_access(workspace_id) ?| array['price','limits','planKey','providerSubscriptionId','reason']) from access_actors where name='full'),'shared summary omits billing details');
select lives_ok($$update public.workout_templates set name='Shared delivery' where id=(select template_id from access_actors where name='full')$$,'shared owner state authorizes delivery');
select lives_ok($$select public.pt_archive_client_relationship(client_id) from access_actors where name='expired'$$,'expired owner may explicitly remove client relationship');
reset role;
select set_config('request.jwt.claim.sub','',true);
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='full'),true);
set local role authenticated;
select lives_ok($$select public.send_conversation_message(c.id,x.owner_id,'pt','Coach','Existing relationship message',false) from public.conversations c join access_actors x on x.client_id=c.client_id where x.name='full'$$,'full coach message allowed');
reset role;
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='grace'),true);
set local role authenticated;
select lives_ok($$select public.send_conversation_message(c.id,x.owner_id,'pt','Coach','Existing relationship message',false) from public.conversations c join access_actors x on x.client_id=c.client_id where x.name='grace'$$,'grace coach message allowed');
reset role;
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='restricted'),true);
set local role authenticated;
select throws_ok($$select public.send_conversation_message(c.id,x.owner_id,'pt','Coach','Existing relationship message',false) from public.conversations c join access_actors x on x.client_id=c.client_id where x.name='restricted'$$,'42501','ACCOUNT_ACCESS_READ_ONLY','restricted coach message denied');
reset role;
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='expired'),true);
set local role authenticated;
reset role;
select set_config('request.jwt.claim.sub','',true);
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='expired'),true);
set local role authenticated;
select throws_ok($$delete from public.workspaces where id=(select workspace_id from access_actors where name='expired')$$,'P0001','This template is already assigned to a client and cannot be deleted. Existing client assignments prevent deletion. Historical records are preserved.','existing assigned-history deletion protection is preserved');
select lives_ok($$delete from public.workspaces where name='Empty access closure'$$,'expired owner can close eligible workspace through guarded FK cascades');
reset role;
select set_config('request.jwt.claim.sub','',true);

create temp table access_bootstrap(name text,id uuid default gen_random_uuid());
grant select on access_bootstrap to authenticated;
insert into access_bootstrap(name) values('onboarding'),('inconsistent');
insert into auth.users(id,email) select id,id::text||'@access.test' from access_bootstrap;
insert into public.pt_profiles(user_id,full_name) select id,'Bootstrap access' from access_bootstrap;
-- Deliberate, transaction-local legacy-corruption fixture; runtime roles cannot
-- disable these triggers. Restore both before invoking authenticated behavior.
alter table public.workspaces disable trigger workspace_account_trial;
alter table public.workspaces disable trigger zz_capacity_admission;
insert into public.workspaces(name,owner_user_id) select 'Legacy missing subscription',id from access_bootstrap where name='inconsistent';
alter table public.workspaces enable trigger workspace_account_trial;
alter table public.workspaces enable trigger zz_capacity_admission;
select set_config('request.jwt.claim.sub',(select id::text from access_bootstrap where name='onboarding'),true);
set local role authenticated;
select is(public.get_my_commercial_access_summary()->>'accessMode','onboarding','no subscription and no workspace means onboarding');
select lives_ok($$select public.create_workspace('First access workspace')$$,'onboarding permits first workspace through original bootstrap');
select is(public.get_my_commercial_access_summary()->>'accessMode','full','first workspace starts canonical trial');
reset role;
select set_config('request.jwt.claim.sub',(select id::text from access_bootstrap where name='inconsistent'),true);
set local role authenticated;
select is(public.get_my_commercial_access_summary()->>'reason','owner_recovery_required','existing workspace with missing subscription has distinct diagnostic');
select is(public.get_my_commercial_access_summary()->>'accessMode','read_only','inconsistent legacy owner fails closed without deleting data');
select throws_ok($$select public.create_workspace('Do not restart trial')$$,'42501','ACCOUNT_ACCESS_OWNER_RECOVERY_REQUIRED','missing history cannot bootstrap another workspace');
reset role;
select set_config('request.jwt.claim.sub','',true);

-- The same client user can retain an unavailable historical relationship and
-- interact independently with another full coach.
insert into public.clients(workspace_id,user_id,status,display_name) select f.workspace_id,e.client_user_id,'active','Second coaching relationship' from access_actors f cross join access_actors e where f.name='full' and e.name='expired';
select set_config('request.jwt.claim.sub',(select client_user_id::text from access_actors where name='expired'),true);
set local role authenticated;
select is((select public.get_client_coaching_access(c.id)->>'serviceMode' from public.clients c join access_actors f on f.workspace_id=c.workspace_id where f.name='full' and c.user_id=auth.uid()),'interactive','another full coaching relationship remains interactive');
select is((select public.get_client_coaching_access(client_id)->>'serviceMode' from access_actors where name='expired'),'unavailable','expired historical relationship remains independently unavailable');
select ok((select public.commercial_storage_write_allowed('medical_documents',client_id::text||'/personal.pdf') from access_actors where name='expired'),'client personal medical upload remains independent');
select ok((select not public.commercial_storage_write_allowed('checkin-photos',client_id::text||'/front.png') from access_actors where name='expired'),'expired coached photo upload is denied');
reset role;
select set_config('request.jwt.claim.sub',(select owner_id::text from access_actors where name='grace'),true);
set local role authenticated;
select ok((select not public.commercial_storage_write_allowed('workspace_branding',workspace_id::text||'/logo.png') from access_actors where name='grace'),'grace denies branding upload');
select ok((select public.commercial_storage_write_allowed('checkin-photos',client_id::text||'/front.png') from access_actors where name='grace'),'grace retains authorized existing delivery uploads');
reset role;
select set_config('request.jwt.claim.sub','',true);
select is((select count(*)::integer from pg_policies where schemaname='storage' and policyname in ('commercial_storage_insert','commercial_storage_update') and permissive='RESTRICTIVE'),2,'storage checks cannot be bypassed by a permissive policy');

update public.workspace_members set role='pt_coach' where workspace_id=(select workspace_id from access_actors where name='grace') and role='assistant_coach';
select set_config('request.jwt.claim.sub',(select m.user_id::text from public.workspace_members m join access_actors x on x.workspace_id=m.workspace_id where x.name='grace' and m.role='pt_coach'),true);
set local role authenticated;
select lives_ok($$select public.set_my_appearance_preferences('dark',true)$$,'personal appearance remains available on suspended legacy membership');
reset role;
select set_config('request.jwt.claim.sub','',true);
select * from finish();
rollback;
