begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
\ir fixtures/paddle_recovery_fixture.psql
create temp table cases(u uuid,extras integer,ordering text);
insert into cases select pg_temp.recovery_owner(extras),extras,ordering from unnest(array[0,1]) extras cross join unnest(array['active-first','completed-first']) ordering;
select is(pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'debt')),'pending','retained debt: '||extras||'/'||ordering) from cases;
create temp table before_state as select u,pg_temp.recovery_counts(u) counts from cases;
select is(pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'active','subscription.updated','2026-10-21T13:00:00Z')),'pending','active alone does not recover: '||extras) from cases where ordering='active-first';
select is(pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'completed','transaction.completed','2026-10-21T12:00:00Z')),'pending','completed before active waits: '||extras) from cases where ordering='completed-first';
select is(pg_temp.recovery_counts(c.u),b.counts,'first event has no canonical or financial effects: '||extras||'/'||ordering) from cases c join before_state b using(u);
select is(pg_temp.obligation(u)->>'reason','settlement_pending','no additional checkout authority after supporting recovery evidence: '||extras||'/'||ordering) from cases;
select is(pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'completed','transaction.completed','2026-10-21T12:00:00Z')),'applied','completed converges with active: '||extras) from cases where ordering='active-first';
select is(pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'active','subscription.updated','2026-10-21T13:00:00Z')),'applied','active converges with completed: '||extras) from cases where ordering='completed-first';
select is(pg_temp.recovery_counts(u)->>'renewal','1','one renewal application: '||extras||'/'||ordering) from cases;
select is(pg_temp.recovery_counts(u)->>'seatPayments',extras::text,'no recovery seat-increase application: '||extras||'/'||ordering) from cases;
select is(pg_temp.recovery_counts(u)->>'approved',extras::text,'approval preserved: '||extras||'/'||ordering) from cases;
select is(pg_temp.recovery_counts(u)->>'capacity',(2+extras)::text,'capacity preserved: '||extras||'/'||ordering) from cases;
select is(pg_temp.recovery_counts(u)->>'status','active','financially recovered: '||extras||'/'||ordering) from cases;
select is(pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'completed','transaction.completed','2026-10-21T12:00:00Z')),'reused','duplicate completed is reused: '||extras||'/'||ordering) from cases;
select is(pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'late-failure','transaction.payment_failed','2026-10-20T12:00:00Z')),'pending','late failed delivery has no financial effect: '||extras||'/'||ordering) from cases;
select is(pg_temp.obligation(u)->>'reason','consumed','late failure cannot reopen consumed debt: '||extras||'/'||ordering) from cases;
select is(pg_temp.recovery_counts(u)->>'renewal','1','duplicate/late evidence cannot double spend: '||extras||'/'||ordering) from cases;
select is(pg_temp.recovery_dispatch(jsonb_set(pg_temp.recovery_observation(u,'completed','transaction.completed','2026-10-21T12:00:00Z'),'{notificationRef}',to_jsonb('synthetic/redelivery/'||u))),'reused','new delivery of same completed event is reused') from cases;
select is(pg_temp.recovery_dispatch(pg_temp.recovery_observation(u,'late-past-due','transaction.past_due')),'pending','late past-due event retained without recovery effects') from cases;
select is(pg_temp.obligation(u)->>'reason','consumed','late past-due cannot reopen consumed renewal') from cases;
select throws_ok($q$update billing_payment_applications_v2 set application_kind='seat_increase' where application_kind='renewal'$q$,'P0001','BILLING_V2_IDENTITY_IMMUTABLE','renewal consumption cannot be repurposed');
create temp table nonfinancial(u uuid,before jsonb);
insert into nonfinancial(u) values(pg_temp.plan_owner());
update nonfinancial set before=pg_temp.recovery_counts(u);
select is(pg_temp.recovery_dispatch((pg_temp.recovery_observation(u,'method','transaction.completed')-'financial')||'{"origin":"subscription_payment_method_change","items":[],"paymentTotals":{"total":0,"paid":0,"balance":0}}'::jsonb),'not_applicable','empty zero-value payment method change is nonfinancial') from nonfinancial;
select is(pg_temp.recovery_counts(u),before,'payment method evidence cannot change commercial authority') from nonfinancial;
select is(pg_temp.obligation(u)->>'reason','none','zero-value payment method update is excluded from debt') from nonfinancial;
select is(pg_temp.lifecycle_dispatch(pg_temp.lifecycle_observation(u,'ordinary-active')),'pending','nonfinancial transaction cannot pay ordinary renewal') from nonfinancial;
select is(pg_temp.lifecycle_dispatch(pg_temp.lifecycle_observation(u,'ordinary-paid','transaction.completed')),'applied','retained payment-method transaction cannot poison ordinary renewal pairing') from nonfinancial;
select is(pg_temp.recovery_counts(u)->>'renewal','1','ordinary financial settlement applies exactly once beside nonfinancial evidence') from nonfinancial;
select * from finish();rollback;
