begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
\ir fixtures/billing_catalogue_fixture.psql
\ir fixtures/billing_v2_legacy_seed.psql
\ir fixtures/billing_cross_ledger_helpers.psql
\ir fixtures/paddle_certification_fixture.psql
\ir fixtures/paddle_webhook_fixture.psql
create temp table cert_actors as select pg_temp.cert_owner() owner,gen_random_uuid() run;
grant select on cert_actors to service_role;
select throws_ok($$select pg_temp.cert_create(owner,run) from cert_actors$$,'P0001','BILLING_CATALOGUE_INCOMPLETE','incomplete catalogue rejected');
select is((select count(*) from billing_paddle_checkout_certification_fixtures),0::bigint,'incomplete admission atomic');
select pg_temp.catalogue_publish(pg_temp.catalogue(k,c)) from unnest(array['launch','growth','scale','coach-seat']) k cross join unnest(array['monthly','annual']) c;
create function pg_temp.cert_policy(flag text) returns void language plpgsql as $$
begin
 if flag='live' then update billing_runtime_policy set entitlement_environment='live';
 elsif flag='sales' then update billing_runtime_policy set paddle_sales_enabled=true;
 else update billing_runtime_policy set paddle_reconciliation_enabled=true; end if;
 perform pg_temp.cert_create(owner,run) from cert_actors;
end $$;
select throws_ok($$select pg_temp.cert_policy('live')$$,'P0001','BILLING_GUARD_ENVIRONMENT_MISMATCH','live rejected');
select throws_ok($$select pg_temp.cert_policy('sales')$$,'P0001','PADDLE_CERTIFICATION_DISABLED','sales true rejected');
select throws_ok($$select pg_temp.cert_policy('reconciliation')$$,'P0001','PADDLE_CERTIFICATION_DISABLED','reconciliation true rejected');
select throws_ok($$select pg_temp.cert_create(gen_random_uuid())$$,'P0001','CERTIFICATION_ACTOR_MISSING','missing account rejected');
create temp table nonqa as select pg_temp.guard_owner() owner;
select throws_ok($$select pg_temp.cert_create(owner) from nonqa$$,'P0001','CERTIFICATION_ACTOR_MISSING','non QA rejected');
update auth.users set raw_user_meta_data='{"repsync_paddle_certification":{"environment":"staging","enabled":true}}' where id=(select owner from nonqa);
select throws_ok($$select pg_temp.cert_create(owner) from nonqa$$,'P0001','CERTIFICATION_ACTOR_MISSING','editable metadata cannot authorize QA');
update auth.users set raw_app_meta_data='{"repsync_paddle_certification":{"environment":"production","enabled":true}}' where id=(select owner from nonqa);
select throws_ok($$select pg_temp.cert_create(owner) from nonqa$$,'P0001','CERTIFICATION_ACTOR_MISSING','production QA marker rejected');
update auth.users set raw_app_meta_data='{"repsync_paddle_certification":{"environment":"staging","enabled":true}}' where id=(select id from actors where name='reduce');
select throws_ok($$select pg_temp.cert_create(id) from actors where name='reduce'$$,'P0001','BILLING_ALREADY_SUBSCRIBED','active paid subscription rejected');
select throws_ok($$select pg_temp.cert_create(owner,run,'launch','monthly',2) from cert_actors$$,'P0001','PADDLE_CHECKOUT_SEAT_POLICY','plan seat bound');
select throws_ok($$select pg_temp.cert_create(owner,run,'scale','annual',6) from cert_actors$$,'P0001','PADDLE_CHECKOUT_SEAT_POLICY','absolute seat bound');
select throws_ok($$select pg_temp.cert_create(owner,run,'growth','weekly') from cert_actors$$,'P0001','PADDLE_CERTIFICATION_INVALID','invalid cadence');
create temp table cert_cases as select k,c,n,pg_temp.cert_owner() owner,gen_random_uuid() run from unnest(array['launch','growth','scale']) k cross join unnest(array['monthly','annual']) c cross join unnest(array[0,1]) n;
create temp table conflict_actors as select k,pg_temp.cert_owner() owner,gen_random_uuid() run from unnest(array['legacy','unmarked']) k;
create temp table protected as select (select jsonb_agg(to_jsonb(t) order by id) from account_subscriptions t) canonical,(select jsonb_agg(resolve_account_entitlements(id)-'computedAt' order by id) from billing_accounts) entitlements,(select jsonb_agg(resolve_account_capacity(owner_user_id,id)-'computedAt' order by id) from billing_accounts) capacity;
set local role service_role;
select lives_ok($$select pg_temp.cert_create(owner,run) from cert_actors$$,'service can create');
reset role;
create temp table first_result as select pg_temp.cert_create(owner,run) result from cert_actors;
select is((select count(*) from billing_paddle_checkout_certification_fixtures),1::bigint,'same run returns same fixture');
select is((select status from billing_checkouts_v2 where operation_id=(select run from cert_actors)),'ready','normal ready transition');
select ok((select result->>'transactionReference'='repsync-cert-'||(result->>'runId') from first_result),'transaction identity generated in SQL');
select ok((select result-array['runId','checkoutId','transactionReference','plan','cadence','additionalCoachSeats']='{}'::jsonb from first_result),'minimal result has no catalogue refs');
select throws_ok($$select pg_temp.cert_create(owner,run,'scale') from cert_actors$$,'P0001','PADDLE_CERTIFICATION_CONFLICT','changed plan same run rejected');
select throws_ok($$select pg_temp.cert_create(owner,run,'growth','annual') from cert_actors$$,'P0001','PADDLE_CERTIFICATION_CONFLICT','changed cadence same run rejected');
select throws_ok($$select pg_temp.cert_create(owner,run,'growth','monthly',1) from cert_actors$$,'P0001','PADDLE_CERTIFICATION_CONFLICT','changed seats same run rejected');
select throws_ok($$select pg_temp.cert_create((select owner from cert_cases limit 1),(select run from cert_actors))$$,'P0001','PADDLE_CERTIFICATION_CONFLICT','different owner same run rejected');
select throws_ok($$select pg_temp.cert_create(owner) from cert_actors$$,'P0001','BILLING_GUARD_CHECKOUT_ALREADY_OPEN','different run open checkout conflict');
select throws_ok($$select pg_temp.guard_checkout(owner,'ls') from cert_actors$$,'P0001','BILLING_GUARD_CHECKOUT_ALREADY_OPEN','fixture blocks legacy checkout');
select lives_ok($$select pg_temp.cert_create(owner,run,k,c,n) from cert_cases$$,'monthly annual base and seats for all plans');
select is((select count(*) from billing_paddle_checkout_certification_fixtures),13::bigint,'all intended fixtures admitted');
select ok((select bool_and(t.status='ready' and t.environment='test' and t.requested_additional_seats=c.n and t.cadence=c.c) from cert_cases c join billing_checkouts_v2 t on t.operation_id=c.run),'all fixture states and quantities match');
select ok((select bool_and(s.base_price_ref=b.provider_price_ref and s.base_product_ref=b.provider_product_ref and s.base_evidence_id=b.catalogue_evidence_id and s.terms_version='2026-09-18' and s.refund_version='2026-09-18' and s.legal_effective_date='2026-09-18') from billing_paddle_checkout_certification_fixtures f join billing_checkouts_v2 t on t.id=f.checkout_id join billing_paddle_checkout_snapshots s on s.checkout_id=t.id join billing_price_mappings b on b.id=t.base_mapping_id),'exact normal base/legal snapshot provenance');
select ok((select bool_and(s.seat_price_ref=b.provider_price_ref and s.seat_product_ref=b.provider_product_ref and s.seat_evidence_id=b.catalogue_evidence_id and b.cadence=t.cadence) from billing_paddle_checkout_certification_fixtures f join billing_checkouts_v2 t on t.id=f.checkout_id join billing_paddle_checkout_snapshots s on s.checkout_id=t.id join billing_price_mappings b on b.id=t.seat_mapping_id),'exact optional seat provenance');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation()||jsonb_build_object('transactionRef',result->>'transactionReference')) from first_result$$,'fixture transaction correlates through existing ingestion');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation('subscription.created','synthetic/fixture-created','synthetic/fixture-created')||jsonb_build_object('transactionCorrelationRef',result->>'transactionReference')) from first_result$$,'fixture creates safe subscription shadow');
select is((select count(*) from billing_subscriptions_v2),1::bigint,'one pending shadow');
select is((select count(*) from billing_paddle_event_observations where disposition='correlated'),2::bigint,'transaction and subscription correlated');
select throws_ok($$select close_paddle_checkout_certification_fixture_v1(gen_random_uuid())$$,'P0001','PADDLE_CERTIFICATION_NOT_FOUND','unmarked close rejected');
create function pg_temp.close_policy(flag text) returns void language plpgsql as $$
begin
 if flag='live' then update billing_runtime_policy set entitlement_environment='live';
 elsif flag='sales' then update billing_runtime_policy set paddle_sales_enabled=true;
 else update billing_runtime_policy set paddle_reconciliation_enabled=true; end if;
 perform close_paddle_checkout_certification_fixture_v1(run) from cert_actors;
end $$;
select throws_ok($$select pg_temp.close_policy('live')$$,'P0001','BILLING_GUARD_ENVIRONMENT_MISMATCH','close live denied');
select throws_ok($$select pg_temp.close_policy('sales')$$,'P0001','PADDLE_CERTIFICATION_DISABLED','close sales true denied');
select throws_ok($$select pg_temp.close_policy('reconciliation')$$,'P0001','PADDLE_CERTIFICATION_DISABLED','close reconciliation true denied');
set local role service_role;
select lives_ok($$select close_paddle_checkout_certification_fixture_v1(run) from cert_actors$$,'service can close');
select lives_ok($$select close_paddle_checkout_certification_fixture_v1(run) from cert_actors$$,'close retry idempotent');
select throws_ok($$delete from billing_paddle_checkout_certification_fixtures$$,'42501','permission denied for table billing_paddle_checkout_certification_fixtures','service direct DML denied');
reset role;
select is((select status from billing_checkouts_v2 where operation_id=(select run from cert_actors)),'expired','normal ready to expired permitted');
select ok((select closed_at is not null from billing_paddle_checkout_certification_fixtures where run_id=(select run from cert_actors)),'close audit stamped');
select throws_ok($$select pg_temp.cert_create(owner,run) from cert_actors$$,'P0001','PADDLE_CERTIFICATION_CLOSED','closed run never resurrected');
select is((select count(*) from billing_paddle_checkout_snapshots),13::bigint,'snapshots retained');
select is((select count(*) from billing_paddle_event_observations),2::bigint,'event history retained');
select is((select count(*) from billing_paddle_event_deliveries),2::bigint,'delivery history retained');
select is((select count(*) from billing_verified_evidence_v2),2::bigint,'verified evidence retained');
select is((select count(*) from billing_subscriptions_v2),1::bigint,'shadow history retained');
select throws_ok($$delete from billing_paddle_checkout_certification_fixtures$$,'P0001','BILLING_V2_HISTORY_IMMUTABLE','marker history immutable');
select throws_ok($$truncate billing_paddle_checkout_certification_fixtures$$,'P0001','BILLING_V2_HISTORY_IMMUTABLE','marker truncate prohibited');
select ok((select relrowsecurity from pg_class where oid='billing_paddle_checkout_certification_fixtures'::regclass),'marker RLS');
select ok((select bool_and(prosecdef and proconfig=array['search_path=pg_catalog, public']) from pg_proc where proname in ('create_paddle_checkout_certification_fixture_v1','close_paddle_checkout_certification_fixture_v1')),'narrow definers fixed search path');
set local role authenticated;
select throws_ok($$select create_paddle_checkout_certification_fixture_v1(null,'growth','monthly',0,null)$$,'42501','permission denied for function create_paddle_checkout_certification_fixture_v1','authenticated creation denied');
select throws_ok($$select close_paddle_checkout_certification_fixture_v1(null)$$,'42501','permission denied for function close_paddle_checkout_certification_fixture_v1','authenticated close denied');
select throws_ok($$insert into billing_paddle_checkout_certification_fixtures(run_id) values(gen_random_uuid())$$,'42501','permission denied for table billing_paddle_checkout_certification_fixtures','browser direct DML denied');
reset role;
set local role anon;
select throws_ok($$select create_paddle_checkout_certification_fixture_v1(null,'growth','monthly',0,null)$$,'42501','permission denied for function create_paddle_checkout_certification_fixture_v1','anonymous creation denied');
select throws_ok($$select close_paddle_checkout_certification_fixture_v1(null)$$,'42501','permission denied for function close_paddle_checkout_certification_fixture_v1','anonymous close denied');
reset role;
select is((select count(*) from billing_payment_applications_v2),0::bigint,'no payment applications');
select is((select count(*) from billing_subscriptions_v2 where account_subscription_id is not null),0::bigint,'no canonical links');
select is((select sum(approved_additional_coach_seats) from billing_subscriptions_v2),0::bigint,'no approved seats');
select ok((select bool_and(reconciliation_status='pending') from billing_subscriptions_v2),'shadows pending only');
select is((select jsonb_agg(to_jsonb(t) order by id) from account_subscriptions t),(select canonical from protected),'canonical history unchanged');
select is((select jsonb_agg(resolve_account_entitlements(id)-'computedAt' order by id) from billing_accounts),(select entitlements from protected),'entitlements unchanged');
select is((select jsonb_agg(resolve_account_capacity(owner_user_id,id)-'computedAt' order by id) from billing_accounts),(select capacity from protected),'capacity unchanged');
select ok((select not paddle_sales_enabled and not paddle_reconciliation_enabled and entitlement_environment='test' from billing_runtime_policy),'policy unchanged');
select pg_temp.guard_checkout(owner,'ls') from conflict_actors where k='legacy';
select throws_ok($$select pg_temp.cert_create(owner,run) from conflict_actors where k='legacy'$$,'P0001','BILLING_GUARD_CHECKOUT_ALREADY_OPEN','legacy blocks fixture');
select billing_v2_admit_checkout(owner,'test','growth','monthly',0,run) from conflict_actors where k='unmarked';
select throws_ok($$select pg_temp.cert_create(owner,run) from conflict_actors where k='unmarked'$$,'P0001','PADDLE_CERTIFICATION_CONFLICT','unmarked admission cannot acquire certification authority');
select throws_ok($$select close_paddle_checkout_certification_fixture_v1(run) from conflict_actors where k='unmarked'$$,'P0001','PADDLE_CERTIFICATION_NOT_FOUND','real unmarked checkout cannot be closed');
update auth.users set raw_app_meta_data='{"repsync_paddle_certification":{"environment":"staging","enabled":true}}' where id=(select id from actors where name='reserved');
select throws_ok($$select pg_temp.cert_create(id) from actors where name='reserved'$$,'P0001','BILLING_GUARD_OPERATION_ALREADY_OPEN','legacy open operation blocks fixture');
update auth.users set raw_app_meta_data='{"repsync_paddle_certification":{"environment":"staging","enabled":true}}' where id=(select owner from nonqa);
delete from pt_profiles where user_id=(select owner from nonqa);
select throws_ok($$select pg_temp.cert_create(owner) from nonqa$$,'P0001','CERTIFICATION_ACTOR_MISSING','QA tag without PT ownership rejected');
select * from finish();
rollback;
