begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
\ir fixtures/billing_catalogue_fixture.psql
\ir fixtures/billing_v2_legacy_seed.psql
\ir fixtures/billing_cross_ledger_helpers.psql
\ir fixtures/paddle_webhook_fixture.psql
select pg_temp.catalogue_publish(pg_temp.catalogue(k,c)) from unnest(array['launch','growth','scale','coach-seat']) k cross join unnest(array['monthly','annual']) c;
update billing_runtime_policy set paddle_sales_enabled=true;
create temp table attempt as select u,begin_paddle_checkout_v1(u,'growth','monthly',0,gen_random_uuid(),true,true,'2026-09-18','2026-09-18') result from (select pg_temp.guard_owner() u) x;
select mark_paddle_checkout_ready_v1(u,(result->>'attemptReference')::uuid,(result->>'operationReference')::uuid,'synthetic/transaction','ready','USD',jsonb_build_array(result->'base')) from attempt;
update billing_runtime_policy set paddle_sales_enabled=false;
create temp table protected as select (select jsonb_agg(to_jsonb(t) order by id) from account_subscriptions t) canonical,(select jsonb_agg(resolve_account_entitlements(id)-'computedAt' order by id) from billing_accounts) entitlements,(select jsonb_agg(resolve_account_capacity(owner_user_id,id)-'computedAt' order by id) from billing_accounts) capacity;
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation())$$,'transaction persists');
select is((select count(*) from billing_webhook_events_v2),1::bigint,'one logical event');
select is((select disposition from billing_paddle_event_observations),'correlated','checkout correlation');
select is((select status from billing_checkouts_v2),'ready','webhook does not transition checkout');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation())$$,'exact replay');
select is((select count(*) from billing_paddle_event_deliveries),1::bigint,'exact repeat deduplicates');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation(n=>'synthetic/delivery2'))$$,'new delivery accepted');
select is((select count(*) from billing_paddle_event_deliveries),2::bigint,'delivery provenance retained');
select is((select count(*) from billing_webhook_events_v2),1::bigint,'commercial logical event not duplicated');
select throws_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation(),repeat('a',64))$$,'P0001','PADDLE_INGRESS_REPLAY_CONFLICT','delivery digest conflict');
select throws_ok($$select pg_temp.webhook_ingest(jsonb_set(pg_temp.webhook_observation(n=>'synthetic/delivery3'),'{items,0,quantity}','2'))$$,'P0001','PADDLE_INGRESS_REPLAY_CONFLICT','logical item conflict');
select throws_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation(e=>'synthetic/other-event'))$$,'P0001','PADDLE_INGRESS_REPLAY_CONFLICT','notification cannot change event');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation('subscription.updated','synthetic/update-first','synthetic/update-first'))$$,'update before create retained');
select is((select count(*) from billing_subscriptions_v2),0::bigint,'unowned update does not guess identity');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation('subscription.created','synthetic/create','synthetic/create'))$$,'create explicitly correlates transaction');
select is((select count(*) from billing_customers_v2),1::bigint,'customer shadow');
select is((select count(*) from billing_subscriptions_v2),1::bigint,'subscription shadow');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation('subscription.created','synthetic/create-again','synthetic/create-again'))$$,'duplicate shadow insertion is safe');
select is((select count(*) from billing_subscriptions_v2),1::bigint,'one shadow identity');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation('subscription.updated','synthetic/new','synthetic/new','2026-09-20T12:00:00.000Z')||'{"status":"paused"}')$$,'new snapshot updates shadow');
select is((select provider_status from billing_subscriptions_v2),'paused','provider state updated');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation('subscription.updated','synthetic/old','synthetic/old','2026-09-20T11:00:00.000Z'))$$,'older update retained');
select is((select provider_status from billing_subscriptions_v2),'paused','older state cannot overwrite');
select throws_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation('subscription.updated','synthetic/wrong-customer','synthetic/wrong-customer')||'{"customerRef":"synthetic/other"}')$$,'P0001','PADDLE_INGRESS_IDENTITY_CONFLICT','identity changes rejected');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation(e=>'synthetic/unknown',n=>'synthetic/unknown')||'{"transactionRef":"synthetic/unknown","subscriptionRef":null}')$$,'unknown transaction evidence retained');
select is((select disposition from billing_paddle_event_observations where observation->>'eventRef'='synthetic/unknown'),'pending','unknown ownership stays pending');
select lives_ok($$select pg_temp.webhook_ingest(jsonb_set(pg_temp.webhook_observation(e=>'synthetic/mismatch',n=>'synthetic/mismatch'),'{items,0,quantity}','2'))$$,'item mismatch retained for review');
select is((select disposition from billing_paddle_event_observations where observation->>'eventRef'='synthetic/mismatch'),'manual_review','quantity mismatch manual review');
select lives_ok($$select pg_temp.webhook_ingest(jsonb_set(pg_temp.webhook_observation(e=>'synthetic/price',n=>'synthetic/price'),'{items,0,priceRef}','"synthetic/unknown-price"'))$$,'unknown price retained');
select is((select disposition from billing_paddle_event_observations where observation->>'eventRef'='synthetic/price'),'manual_review','unknown price no authority');
select throws_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation()||'{"environment":"live"}')$$,'P0001','PADDLE_INGRESS_SCOPE','environment rejected');
select throws_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation()||'{"unreviewed":"payload"}')$$,'P0001','BILLING_PROOF_INVALID','closed sanitized facts');
select ok((select bool_and(not payment_authority) from billing_verified_evidence_v2),'event receipts never payment authority');
select is((select count(*) from billing_payment_applications_v2),0::bigint,'no payments');
select is((select count(*) from billing_subscriptions_v2 where account_subscription_id is not null),0::bigint,'no canonical links');
select is((select sum(approved_additional_coach_seats) from billing_subscriptions_v2),0::bigint,'no approved seats');
select ok((select not paddle_sales_enabled and not paddle_reconciliation_enabled from billing_runtime_policy),'flags remain false');
select is((select jsonb_agg(to_jsonb(t) order by id) from account_subscriptions t),(select canonical from protected),'canonical unchanged');
select is((select jsonb_agg(resolve_account_entitlements(id)-'computedAt' order by id) from billing_accounts),(select entitlements from protected),'entitlements unchanged');
select is((select jsonb_agg(resolve_account_capacity(owner_user_id,id)-'computedAt' order by id) from billing_accounts),(select capacity from protected),'capacity unchanged');
select ok(not has_function_privilege('anon','ingest_verified_paddle_event_v1(jsonb,text,text,jsonb)','execute') and not has_function_privilege('authenticated','ingest_verified_paddle_event_v1(jsonb,text,text,jsonb)','execute'),'client execute denied');
select ok(has_function_privilege('service_role','ingest_verified_paddle_event_v1(jsonb,text,text,jsonb)','execute'),'service execution granted');
select ok((select proconfig=array['search_path=pg_catalog, public'] from pg_proc where proname='ingest_verified_paddle_event_v1'),'fixed path');
select ok((select bool_and(relrowsecurity) from pg_class where relname in ('billing_paddle_event_observations','billing_paddle_event_deliveries')),'RLS intact');
select ok(not has_table_privilege('service_role','billing_paddle_event_observations','insert') and not has_table_privilege('authenticated','billing_paddle_event_deliveries','insert'),'direct DML denied');
select throws_ok($$delete from billing_paddle_event_deliveries$$,'P0001','BILLING_V2_HISTORY_IMMUTABLE','delivery immutable');
select lives_ok($$select pg_temp.webhook_ingest(jsonb_set(pg_temp.webhook_observation(e=>'synthetic/product',n=>'synthetic/product'),'{items,0,productRef}','"synthetic/wrong-product"'))$$,'product mismatch retained');
select is((select disposition from billing_paddle_event_observations where observation->>'eventRef'='synthetic/product'),'manual_review','product association required');
select lives_ok($$select pg_temp.webhook_ingest(jsonb_set(pg_temp.webhook_observation(e=>'synthetic/duplicate',n=>'synthetic/duplicate'),'{items}',jsonb_build_array(pg_temp.webhook_observation()#>'{items,0}',pg_temp.webhook_observation()#>'{items,0}')))$$,'duplicate items retained');
select is((select disposition from billing_paddle_event_observations where observation->>'eventRef'='synthetic/duplicate'),'manual_review','duplicate logical role rejected');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation('subscription.updated','synthetic/equal','synthetic/equal','2026-09-20T12:00:00.000Z'))$$,'equal timestamp conflict retained');
select is((select disposition from billing_paddle_event_observations where observation->>'eventRef'='synthetic/equal'),'manual_review','equal timestamp does not pick a winner');
set local role authenticated;
select throws_ok($$select public.ingest_verified_paddle_event_v1('{}',repeat('a',64),'synthetic/n','{}')$$,'42501','permission denied for function ingest_verified_paddle_event_v1','actual client execution denied');
select throws_ok($$insert into public.billing_paddle_event_deliveries(notification_ref) values('synthetic/client')$$,'42501','permission denied for table billing_paddle_event_deliveries','actual client DML denied');
reset role;
set local role service_role;
select throws_ok($$insert into public.billing_paddle_event_deliveries(notification_ref) values('synthetic/service')$$,'42501','permission denied for table billing_paddle_event_deliveries','actual service DML denied');
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation(e=>'synthetic/service',n=>'synthetic/service'))$$,'actual service RPC executes');
reset role;
update billing_runtime_policy set paddle_sales_enabled=true;
create temp table ambiguous_attempt as select u,begin_paddle_checkout_v1(u,'growth','monthly',0,gen_random_uuid(),true,true,'2026-09-18','2026-09-18') result from (select pg_temp.guard_owner() u) x;
select mark_paddle_checkout_ambiguous_v1(u,(result->>'attemptReference')::uuid,(result->>'operationReference')::uuid) from ambiguous_attempt;
update billing_runtime_policy set paddle_sales_enabled=false;
select lives_ok($$select pg_temp.webhook_ingest(pg_temp.webhook_observation(e=>'synthetic/ambiguous',n=>'synthetic/ambiguous')||'{"transactionRef":"synthetic/ambiguous-transaction","subscriptionRef":null,"customerRef":null}')$$,'unidentified ambiguous transaction retained');
select is((select count(*) from billing_checkouts_v2 where status='ambiguous'),1::bigint,'verified event cannot retry or resolve ambiguous checkout');
select is((select disposition from billing_paddle_event_observations where observation->>'eventRef'='synthetic/ambiguous'),'pending','ambiguous ownership not guessed');
select * from finish();
rollback;
