"""Compare DB-01 legacy manifests, permitting only DB-02 guard definitions.

Usage: python scripts/verify-billing-cross-ledger-manifest.py before.json after.json
The input manifests are generated by billing_v2_legacy_manifest.psql locally.
"""

import json
import sys
from pathlib import Path


PREAMBLES = {
    "begin_my_billing_checkout_attempt": "perform public.billing_guard_legacy_entry('checkout_owner',null,p_environment,p_operation_id);",
    "expire_stale_billing_checkout_attempts": "perform public.billing_guard_expire_checkouts(p_account);",
    "complete_billing_checkout_attempt": "perform public.billing_guard_legacy_entry('checkout_effect',p_attempt);",
    "fail_billing_checkout_attempt": "perform public.billing_guard_legacy_entry('checkout_cleanup',p_attempt);",
    "begin_billing_plan_change": "perform public.billing_guard_legacy_entry('legacy_plan',p_owner,p_environment,p_operation);",
    "begin_billing_seat_quantity": "perform public.billing_guard_legacy_entry('legacy_seat',p_owner,p_environment,p_operation);",
    "begin_cancel_billing_plan_change": "perform public.billing_guard_legacy_entry('owner_effect',p_owner,p_environment);",
    "begin_cancel_billing_seat_quantity": "perform public.billing_guard_legacy_entry('owner_effect',p_owner,p_environment);",
    "reconcile_billing_provider_subscription": "perform public.billing_guard_legacy_entry('reconcile',p_delivery);",
    "apply_verified_billing_plan_change": "perform public.billing_guard_legacy_entry('apply_plan',p_operation);",
    "apply_verified_billing_seat_quantity": "perform public.billing_guard_legacy_entry('apply_seat',p_subscription);",
}
TRIGGERS = {
    "billing_checkout_attempts": ("a00_billing_checkout_guard", "billing_guard_checkout_row"),
    "billing_plan_change_operations": ("a00_billing_operation_guard", "billing_guard_operation_row"),
    "billing_seat_quantity_operations": ("a00_billing_operation_guard", "billing_guard_operation_row"),
    "billing_provider_subscriptions": ("a00_billing_subscription_guard", "billing_guard_subscription_row"),
}
NEW_FUNCTIONS = {
    "billing_guard_actor", "billing_guard_lock", "billing_guard_expire_checkouts",
    "billing_guard_checkout_conflict", "billing_guard_operation_conflict",
    "billing_guard_claim_canonical", "billing_guard_checkout_row",
    "billing_guard_operation_row", "billing_guard_subscription_row",
    "billing_guard_payment_row", "billing_guard_legacy_entry",
}


def compare(before, after):
    assert before.keys() == after.keys(), "Manifest surfaces changed"
    for name in before:
        if name == "legacy_functions":
            continue
        if name in TRIGGERS:
            trigger, function = TRIGGERS[name]
            expected = f"CREATE TRIGGER {trigger} BEFORE INSERT OR UPDATE ON public.{name} FOR EACH ROW EXECUTE FUNCTION {function}()"
            definitions = after[name]["definition"]["triggers"]
            assert definitions.count(expected) == 1, f"Unexpected guard definition: {name}"
            definitions.remove(expected)
        assert before[name] == after[name], f"Legacy rows/output/schema differs: {name}"
    originals = {r[0]: r for r in before["legacy_functions"]}
    updated = {r[0]: r for r in after["legacy_functions"]}
    added = set(updated) - set(originals)
    assert {s.split("(")[0] for s in added} == NEW_FUNCTIONS, "Unexpected new functions"
    assert len(added) == len(NEW_FUNCTIONS), "Unexpected new overload"
    changed = 0
    for signature, old in originals.items():
        new = updated[signature]
        name = signature.split("(")[0]
        if name in PREAMBLES:
            block = "  -- BILLING-DB-02 BEGIN\n  " + PREAMBLES[name] + "\n  -- BILLING-DB-02 END\n"
            assert new[1].count(block) == 1, f"Guard not found exactly once: {signature}"
            new[1] = new[1].replace(block, "", 1)
            changed += 1
        assert old == new, f"Legacy function body or grants changed: {signature}"
    assert changed == len(PREAMBLES), "Missing legacy guard preamble"
    print(json.dumps({
        "semantic_differences": 0,
        "tables": len(before) - 3,
        "rows": sum(len(v["rows"]) for v in before.values() if isinstance(v, dict)),
        "original_functions": len(originals),
        "unchanged_proof_bodies_and_grants": True,
        "intentional_entry_preambles": changed,
        "intentional_legacy_triggers": len(TRIGGERS),
        "accounts": len(before["entitlements"]),
    }, indent=2))


if __name__ == "__main__":
    compare(*(json.loads(Path(p).read_text(encoding="utf-8-sig")) for p in sys.argv[1:]))
